#!/usr/bin/env bash
# First-time setup: generates a .env file with cryptographically random secrets.
# Run once before the first deployment.
set -euo pipefail

ENV_FILE="$(dirname "$0")/.env"

if [[ -f "$ENV_FILE" ]]; then
    echo "Warning: .env already exists. Overwrite? [y/N]"
    read -r answer
    [[ "$answer" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 0; }
fi

postgres_password=$(openssl rand -hex 24)
jwt_key=$(openssl rand -hex 32)
encryption_key=$(openssl rand -hex 16)  # 16 bytes hex = 32 hex chars = 32-char ASCII key

cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
# Keep this file secret – it is listed in .gitignore

POSTGRES_PASSWORD=${postgres_password}
JWT_KEY=${jwt_key}
ENCRYPTION_KEY=${encryption_key}
CHECKIN_INTERVAL_MINUTES=30
EOF

chmod 600 "$ENV_FILE"
echo "✓ .env created with random secrets."
echo ""
echo "Next steps:"
echo "  1. (Optional) Edit .env to adjust CHECKIN_INTERVAL_MINUTES."
echo "  2. docker compose up -d --build"
echo "  3. For HTTPS: place certs in ./certs/ and run:"
echo "       docker compose -f docker-compose.yml -f docker-compose.https.yml up -d --build"
